spring.application.name=demo

#PostgreSQL connection
spring.datasource.url=jdbs:postgresql://localhost:5432/tennis_scoreboard
spring.datasource.username=postgres
spring.datasource.password=postgres

#Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
